### ISSUE TITLE
[Bug]: error on press Hot Key. It works good on mouse click in explorer menu

### ISSUE THREAD

**Issue by MaksimDmitrenko** [Power-Maverick/DataverseDevTools-VSCode#102]
### What happened?

Error on press Hot Key. It works good on mouse click in explorer menu.

### What version of the tool are you using?

2.1.1

### What version of Visual Studio Code are you running?

1.77.1 

### Any relevant session id from VSCode?

e2d653a5-e4c7-444e-bab7-a63e0da1808e1680866921766

### Relevant log output

```shell
Error occured in uploadWebResource command. 
Error code: undefined. 
Error message: Cannot read properties of undefined (reading 'fsPath'). 
Error stack: TypeError: Cannot read properties of undefined (reading 'fsPath')
	at \out\commands\registerCommands.js:162:58
	at Generator.next (<anonymous>)
	at \out\commands\registerCommands.js:31:71
	at new Promise (<anonymous>)
	at __awaiter (\out\commands\registerCommands.js:27:12)
	at callback (\out\commands\registerCommands.js:160:32)
	at m.h (\out\vs\workbench\api\node\extensionHostProcess.js:98:125797)
	at m.$executeContributedCommand (\out\vs\workbench\api\node\extensionHostProcess.js:98:126701)
	at c.N (\out\vs\workbench\api\node\extensionHostProcess.js:108:11655)
	at c.M (\out\vs\workbench\api\node\extensionHostProcess.js:108:11373)
	at c.H (\out\vs\workbench\api\node\extensionHostProcess.js:108:10454)
	at c.G (\out\vs\workbench\api\node\extensionHostProcess.js:108:9432)
	at \out\vs\workbench\api\node\extensionHostProcess.js:108:8220
	at E.invoke (\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
	at h.deliver (\out\vs\workbench\api\node\extensionHostProcess.js:63:2121)
	at n.fire (\out\vs\workbench\api\node\extensionHostProcess.js:63:1729)
	at p.fire (\out\vs\workbench\api\node\extensionHostProcess.js:72:14916)
	at \out\vs\workbench\api\node\extensionHostProcess.js:124:16654
	at E.invoke (\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
	at h.deliver (\out\vs\workbench\api\node\extensionHostProcess.js:63:2121)
	at n.fire (\out\vs\workbench\api\node\extensionHostProcess.js:63:1729)
	at p.fire (\out\vs\workbench\api\node\extensionHostProcess.js:72:14916)
	at MessagePortMain.<anonymous> (\out\vs\workbench\api\node\extensionHostProcess.js:124:14780)
	at MessagePortMain.emit (node:events:526:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364).
```

**Comment by Power-Maverick** [comment]
Resolution: remove the hotkey
Reason: Need the context of the WR which we don't get from the hotkey implementation
Planning to fix: next release

**Comment by MaksimDmitrenko** [comment]
Of course I can use the right mouse button, but this should work using hotkeys. Using hot keys is very convenient.
