### ISSUE TITLE
[Bug]: Trying to upload new resource from subfolder fails

### ISSUE THREAD

**Issue by erickalves05** [Power-Maverick/DataverseDevTools-VSCode#120]
### What happened?

When opening a root folder on VS Code and the TS project is in a subfolder the selected resource should be uploaded.

<img width="233" alt="image" src="https://github.com/Power-Maverick/DataverseDevTools-VSCode/assets/1979369/190616ae-f767-4177-a99e-9fed10eb7606">

### What version of the tool are you using?

2.1.1

### What version of Visual Studio Code are you running?

1.78.2

### Any relevant session id from VSCode?

e92a881c-4b68-4efa-8867-d84be7032aa91685456000736

### Relevant log output

```shell
Error occured in uploadWebResource command. 
Error code: undefined. 
Error message: Cannot read properties of undefined (reading 'environmentUrl'). 
Error stack: TypeError: Cannot read properties of undefined (reading 'environmentUrl')
    at RequestHelper.<anonymous> (\out\helpers\requestHelper.js:32:57)
    at Generator.next (<anonymous>)
    at \out\helpers\requestHelper.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (\out\helpers\requestHelper.js:4:12)
    at RequestHelper.requestData (\out\helpers\requestHelper.js:29:16)
    at DataverseHelper.<anonymous> (\out\helpers\dataverseHelper.js:239:49)
    at Generator.next (<anonymous>)
    at \out\helpers\dataverseHelper.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (\out\helpers\dataverseHelper.js:27:12)
    at DataverseHelper.getSolutions (\out\helpers\dataverseHelper.js:238:16)
    at WebResourceHelper.<anonymous> (\out\helpers\webResourceHelper.js:492:51)
    at Generator.next (<anonymous>)
    at \out\helpers\webResourceHelper.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (\out\helpers\webResourceHelper.js:27:12)
    at WebResourceHelper.webResourceCreateWizard (\out\helpers\webResourceHelper.js:490:16)
    at WebResourceHelper.<anonymous> (\out\helpers\webResourceHelper.js:395:43)
    at Generator.next (<anonymous>)
    at \out\helpers\webResourceHelper.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (\out\helpers\webResourceHelper.js:27:12)
    at \out\helpers\webResourceHelper.js:375:37
    at D.d (\out\vs\workbench\api\node\extensionHostProcess.js:98:45036)
    at D.withProgress (\out\vs\workbench\api\node\extensionHostProcess.js:98:44879)
    at Object.withProgress (\out\vs\workbench\api\node\extensionHostProcess.js:116:34519)
    at WebResourceHelper.<anonymous> (\out\helpers\webResourceHelper.js:372:34)
    at Generator.next (<anonymous>)
    at \out\helpers\webResourceHelper.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (\out\helpers\webResourceHelper.js:27:12)
    at WebResourceHelper.uploadWebResourceInternal (\out\helpers\webResourceHelper.js:370:16)
    at WebResourceHelper.<anonymous> (\out\helpers\webResourceHelper.js:72:47)
    at Generator.next (<anonymous>)
    at fulfilled (\out\helpers\webResourceHelper.js:28:58).
```

**Comment by Power-Maverick** [comment]
Were you connected to an environment. Can you share some details on the upload process?
