### ISSUE TITLE
[Bug]: Microsoft Login Prompt Fails

### ISSUE THREAD

**Issue by SescoEnvDev** [Power-Maverick/DataverseDevTools-VSCode#127]
### What happened?

Attempting to log in with the "Microsoft Login Prompt" option fails. See log info below. 

### What version of the tool are you using?

v2.1.4

### What version of Visual Studio Code are you running?

1.81.0

### Any relevant session id from VSCode?

ea3aef58-532a-4e53-9ca8-abfff76c895a1691676941237

### Relevant log output

```shell
Error occured in connectDataverse command. 
Error code: undefined. 
Error message: unauthorized_client: 700016 - [2023-08-10 16:42:25Z]: AADSTS700016: Application with identifier '1cab452e-c5f4-4fc9-8efb-28d54031db71' was not found in the directory 'SESCO LLC'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: 08f98f6a-3e9c-4a71-88c4-b1e07e5bcf00
Correlation ID: 8521dccc-820f-4df9-92f9-371093750b41
Timestamp: 2023-08-10 16:42:25Z - Correlation ID: 8521dccc-820f-4df9-92f9-371093750b41 - Trace ID: 08f98f6a-3e9c-4a71-88c4-b1e07e5bcf00. 
Error stack: ServerError: unauthorized_client: 700016 - [2023-08-10 16:42:25Z]: AADSTS700016: Application with identifier '1cab452e-c5f4-4fc9-8efb-28d54031db71' was not found in the directory 'SESCO LLC'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: 08f98f6a-3e9c-4a71-88c4-b1e07e5bcf00
Correlation ID: 8521dccc-820f-4df9-92f9-371093750b41
Timestamp: 2023-08-10 16:42:25Z - Correlation ID: 8521dccc-820f-4df9-92f9-371093750b41 - Trace ID: 08f98f6a-3e9c-4a71-88c4-b1e07e5bcf00
    at ServerError.AuthError [as constructor] (\node_modules\@azure\msal-common\dist\index.cjs.js:514:24)
    at new ServerError (\node_modules\@azure\msal-common\dist\index.cjs.js:3338:28)
    at ResponseHandler.validateTokenResponse (\node_modules\@azure\msal-common\dist\index.cjs.js:4976:19)
    at ClientCredentialClient.<anonymous> (\node_modules\@azure\msal-common\dist\index.cjs.js:6404:41)
    at step (\node_modules\@azure\msal-common\dist\index.cjs.js:79:23)
    at Object.next (\node_modules\@azure\msal-common\dist\index.cjs.js:60:53)
    at fulfilled (\node_modules\@azure\msal-common\dist\index.cjs.js:50:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5).
```

**Comment by SescoEnvDev** [comment]
Therre was a typo in my URL. Will attempt with corrected URL, and post the results.

**Comment by SescoEnvDev** [comment]
Closed due to user error. Opened new issue with updated error.
