### ISSUE TITLE
[Bug]: Microsoft Login Prompt fails

### ISSUE THREAD

**Issue by SescoEnvDev** [Power-Maverick/DataverseDevTools-VSCode#128]
### What happened?

Using the *correct* URL this time, I attempted to log in with the Microsoft Login Prompt option.
I received the error message that appears in the below log. 
I am logged in to Azure in the correct tenant, and have successfully connected to Dataverse/Power Platform with other extensions.
There is an existing app registration for VScode in Azure, as well as the relevant Dataverse environment.

### What version of the tool are you using?

v2.1.4

### What version of Visual Studio Code are you running?

1.81.0

### Any relevant session id from VSCode?

ea3aef58-532a-4e53-9ca8-abfff76c895a1691676941237

### Relevant log output

```shell
Error occured in addConnection command. 
Error code: undefined. 
Error message: AADSTS500011: The resource principal named [REDACTED FOR PRIVACY] was not found in the tenant named [REDACTED FOR PRIVACY]. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: e895a9cc-2da3-40db-ad5b-0200350ff200
Correlation ID: 471c00f6-8a57-4ea4-9566-9e6676cb0183
Timestamp: 2023-08-10 16:50:43Z. 
Error stack: Error: AADSTS500011: The resource principal named [REDACTED FOR PRIVACY] was not found in the tenant named [REDACTED FOR PRIVACY]. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: e895a9cc-2da3-40db-ad5b-0200350ff200
Correlation ID: 471c00f6-8a57-4ea4-9566-9e6676cb0183
Timestamp: 2023-08-10 16:50:43Z
    at \out\login\server.js:212:15
    at Generator.next (<anonymous>)
    at \out\login\server.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (\out\login\server.js:27:12)
    at callback (\out\login\server.js:193:12)
    at Server.<anonymous> (\out\login\server.js:111:38)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:980:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17).
```

**Comment by Power-Maverick** [comment]
Based on the error looks like you are not using the right combination. Please ensure correct credentials are used. Closing this issue but feel free to re-open if this is still an issue.
