### ISSUE TITLE
[Bug]: Dataverse DevTools: Error occured - undefined. Please report it on GitHub.

### ISSUE THREAD

**Issue by minamzakhary** [Power-Maverick/DataverseDevTools-VSCode#131]
### What happened?

add a ts file

### What version of the tool are you using?

v2.1.4 

### Any relevant session id from VSCode?

21dd6541-29b3-4fd1-b301-fd5d174c8e1c1695675881190

### Relevant log output

```shell
Error occured in createTSFile command. 
Error code: undefined. 
Error message: Cannot read properties of undefined (reading 'fsPath'). 
Error stack: TypeError: Cannot read properties of undefined (reading 'fsPath')
    at \out\commands\registerCommands.js:204:64
    at Generator.next (<anonymous>)
    at \out\commands\registerCommands.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (\out\commands\registerCommands.js:27:12)
    at callback (\out\commands\registerCommands.js:202:32)
    at r.h (\out\vs\workbench\api\node\extensionHostProcess.js:107:82744)
    at r.$executeContributedCommand (\out\vs\workbench\api\node\extensionHostProcess.js:107:83604)
    at i.N (\out\vs\workbench\api\node\extensionHostProcess.js:116:10813)
    at i.M (\out\vs\workbench\api\node\extensionHostProcess.js:116:10579)
    at i.H (\out\vs\workbench\api\node\extensionHostProcess.js:116:9660)
    at i.G (\out\vs\workbench\api\node\extensionHostProcess.js:116:8736)
    at n.value (\out\vs\workbench\api\node\extensionHostProcess.js:116:7566)
    at m.w (\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at m.fire (\out\vs\workbench\api\node\extensionHostProcess.js:63:2119)
    at w.fire (\out\vs\workbench\api\node\extensionHostProcess.js:79:13940)
    at n.value (\out\vs\workbench\api\node\extensionHostProcess.js:135:7901)
    at m.w (\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at m.fire (\out\vs\workbench\api\node\extensionHostProcess.js:63:2119)
    at w.fire (\out\vs\workbench\api\node\extensionHostProcess.js:79:13940)
    at MessagePortMain.<anonymous> (\out\vs\workbench\api\node\extensionHostProcess.js:135:6181)
    at MessagePortMain.emit (node:events:513:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367).
```

**Comment by Power-Maverick** [comment]
I will look into it this weekend. Thanks for letting me know.

**Comment by Power-Maverick** [comment]
I hope the issue has been resolved. Upgrade to v2.1.5. 
Please lemme know if you are running into issues.

**Comment by Power-Maverick** [comment]
Not resolved.. WIP

**Comment by Power-Maverick** [comment]
Issue should be resolved now. Make sure that v2.1.10 is installed.
