### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ppablo08** [Power-Maverick/DataverseDevTools-VSCode#161]
### What happened?

Error

### What version of the tool are you using?

Power Platform Toolbox

### What version of Visual Studio Code are you running?

1.88.1

### Any relevant session id from VSCode?

3c310f78-ac77-4cd4-9afc-95ddd2ade8ed1714555240069

### Relevant log output

```shell
VSCode version: 1.88.1. 
Extension version: 2.2.0. 
Error occured in connectDataverse command. 
Error code: undefined. 
Error message: Cannot read properties of undefined (reading 'label'). 
Error stack: TypeError: Cannot read properties of undefined (reading 'label')
    at t.DataverseHelper.<anonymous> (c:\Users\pospino\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:719985)
    at Generator.next (<anonymous>)
    at c:\Users\pospino\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:718699
    at new Promise (<anonymous>)
    at o (c:\Users\pospino\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:718444)
    at t.DataverseHelper.connectToDataverse (c:\Users\pospino\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:719916)
    at c:\Users\pospino\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:705576
    at Generator.next (<anonymous>)
    at c:\Users\pospino\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:703425
    at new Promise (<anonymous>)
    at o (c:\Users\pospino\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:703170)
    at callback (c:\Users\pospino\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:705528)
    at d.h (c:\Users\pospino\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:186874)
    at d.$executeContributedCommand (c:\Users\pospino\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:187734)
    at u.S (c:\Users\pospino\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:5502)
    at u.Q (c:\Users\pospino\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:5268)
    at u.M (c:\Users\pospino\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:4361)
    at u.L (c:\Users\pospino\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:3440)
    at o.value (c:\Users\pospino\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:2227)
    at s.y (c:\Users\pospino\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:659)
    at s.fire (c:\Users\pospino\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:876)
    at r.fire (c:\Users\pospino\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14173)
    at o.value (c:\Users\pospino\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:175:8018)
    at s.y (c:\Users\pospino\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:659)
    at s.fire (c:\Users\pospino\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:876)
    at r.fire (c:\Users\pospino\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14173)
    at MessagePortMain.<anonymous> (c:\Users\pospino\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:175:6298)
    at MessagePortMain.emit (node:events:517:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285).
```

**Comment by Power-Maverick** [comment]
Need more details here. What did you try? What type of connection it was? Please provide more details.
