### ISSUE TITLE
[Bug]: Cant connect to my DEV environment

### ISSUE THREAD

**Issue by Ks532701** [Power-Maverick/DataverseDevTools-VSCode#166]
### What happened?

Iam trying to login to my environment, with client & secret key 

### What version of the tool are you using?

2.2.0

### What version of Visual Studio Code are you running?

1.91.0

### Any relevant session id from VSCode?

6f4623d1-06a5-43a2-907f-f227d996bf721720425780892

### Relevant log output

```shell
VSCode version: 1.91.0. 
Extension version: 2.2.0. 
Error occured in connectDataverse command. 
Error code: undefined. 
Error message: invalid_client: 7000215 - [2024-07-08 08:08:48Z]: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'b08e2b27-0b51-4da2-8c2e-decce73ce3f7'. Trace ID: 70fd961d-4f30-4cce-ab3d-de29fa23c900 Correlation ID: 6e46875c-70ea-4650-9102-8a32293f4fba Timestamp: 2024-07-08 08:08:48Z - Correlation ID: 6e46875c-70ea-4650-9102-8a32293f4fba - Trace ID: 70fd961d-4f30-4cce-ab3d-de29fa23c900. 
Error stack: ServerError: invalid_client: 7000215 - [2024-07-08 08:08:48Z]: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'b08e2b27-0b51-4da2-8c2e-decce73ce3f7'. Trace ID: 70fd961d-4f30-4cce-ab3d-de29fa23c900 Correlation ID: 6e46875c-70ea-4650-9102-8a32293f4fba Timestamp: 2024-07-08 08:08:48Z - Correlation ID: 6e46875c-70ea-4650-9102-8a32293f4fba - Trace ID: 70fd961d-4f30-4cce-ab3d-de29fa23c900
	at t [as constructor] (c:\Users\965345\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:10011)
	at new t (c:\Users\965345\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:67784)
	at e.validateTokenResponse (c:\Users\965345\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:91558)
	at t.<anonymous> (c:\Users\965345\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:175319)
	at c:\Users\965345\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:2482
	at Object.next (c:\Users\965345\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:2587)
	at o (c:\Users\965345\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:1326)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5).
```

**Comment by AngusWri** [comment]
Looks like your client secret value is invalid...
Be sure you are entering at on the correct prompt or its not expired

**Comment by Power-Maverick** [comment]
As @Luxahule mentioned please check your client id and secret
