### ISSUE TITLE
[Bug]: Cannot login after enabled microsoft MFA

### ISSUE THREAD

**Issue by emibanana** [Power-Maverick/DataverseDevTools-VSCode#173]
### What happened?

Cannot login after enabled microsoft MFA

### What version of the tool are you using?

v2.2.0

### What version of Visual Studio Code are you running?

1.85.2

### Any relevant session id from VSCode?

1142e4bd-54bc-4d41-94a4-c561b94f14e11729166527923

### Relevant log output

```shell
VSCode version: 1.85.2. 
Extension version: 2.2.0. 
Error occured in showEntityDetails command. 
Error code: undefined. 
Error message: Cannot read properties of undefined (reading 'environmentUrl'). 
Error stack: TypeError: Cannot read properties of undefined (reading 'environmentUrl')
	at t.RequestHelper.<anonymous> (c:\Users\Zixi Deng\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:735666)
	at Generator.next (<anonymous>)
	at c:\Users\Zixi Deng\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:735234
	at new Promise (<anonymous>)
	at i (c:\Users\Zixi Deng\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:734979)
	at t.RequestHelper.requestData (c:\Users\Zixi Deng\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:735554)
	at t.DataverseHelper.<anonymous> (c:\Users\Zixi Deng\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:722131)
	at Generator.next (<anonymous>)
	at c:\Users\Zixi Deng\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:718699
	at new Promise (<anonymous>)
	at o (c:\Users\Zixi Deng\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:718444)
	at t.DataverseHelper.getAttributesForEntity (c:\Users\Zixi Deng\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:722070)
	at t.DataverseHelper.<anonymous> (c:\Users\Zixi Deng\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:723720)
	at Generator.next (<anonymous>)
	at c:\Users\Zixi Deng\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:718699
	at new Promise (<anonymous>)
	at o (c:\Users\Zixi Deng\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:718444)
	at t.DataverseHelper.showEntityDetails (c:\Users\Zixi Deng\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:723617)
	at c:\Users\Zixi Deng\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:706165
	at Generator.next (<anonymous>)
	at c:\Users\Zixi Deng\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:703425
	at new Promise (<anonymous>)
	at o (c:\Users\Zixi Deng\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:703170)
	at callback (c:\Users\Zixi Deng\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.0\dist\extension.js:2:706101)
	at d.h (c:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:140094)
	at d.$executeContributedCommand (c:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:140954)
	at l.S (c:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:10829)
	at l.Q (c:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:10595)
	at l.M (c:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:9685)
	at l.L (c:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:8903)
	at f.value (c:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:7567)
	at n.y (c:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
	at n.fire (c:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
	at o.fire (c:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:14039)
	at f.value (c:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:7903)
	at n.y (c:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
	at n.fire (c:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
	at o.fire (c:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:14039)
	at MessagePortMain.<anonymous> (c:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:6183)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367).
```

**Comment by Power-Maverick** [comment]
what type of connection were you creating?

**Comment by emibanana** [comment]
> what type of connection were you creating?

Hi, i tried using both username + password and microsoft login prompt, both gave the same error

**Comment by emibanana** [comment]
> what type of connection were you creating?

I have now installed a previous version of this plugin (says 10 months old) and now the issue is fixed.

I believe this is a good indication for where is the issue.

**Comment by Power-Maverick** [comment]
with the latest version; can you add another connection to the same environment but with a different name? Use Microsoft Login Prompt as that will handle the MFA. Lemme know how that goes.

**Comment by emibanana** [comment]
> with the latest version; can you add another connection to the same environment but with a different name? Use Microsoft Login Prompt as that will handle the MFA. Lemme know how that goes.

Yes sorry for the late reply. i can add new name but it gives the same result. unless there is a new version that fixed the issue (i havent update since i post)

**Comment by Power-Maverick** [comment]
Yeah make sure you are on latest version. If it still fails I can try to investigate what's happening more.
