### ISSUE TITLE
[Bug]: Error in uploadWebResource 

### ISSUE THREAD

**Issue by YasinGo** [Power-Maverick/DataverseDevTools-VSCode#200]
### What happened?

There is no possibility to upload and publish my JS Code. 

### What version of the tool are you using?

v2.2.1

### Any relevant session id from VSCode?

acd4a751-23ed-4028-946d-a8819cb859241733908322778

### Relevant log output

```shell
VSCode version: 1.95.3. 
Extension version: 2.2.1. 
Error occured in uploadWebResource command. 
Error code: undefined. 
Error message: Cannot set properties of undefined (setting '@_version'). 
Error stack: TypeError: Cannot set properties of undefined (setting '@_version')
	at t.xmlToJSON (c:\Users\YasinGörgülü\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.1\dist\extension.js:2:801897)
	at t.WebResourceHelper.<anonymous> (c:\Users\YasinGörgülü\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.1\dist\extension.js:2:762308)
	at Generator.next (<anonymous>)
	at o (c:\Users\YasinGörgülü\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.1\dist\extension.js:2:751513).
```

**Comment by mksa1** [comment]
I'm experiencing the same issue. Relevant log informaiton below:

VSCode version: 1.96.0. 
Extension version: 2.2.1. 
Error occured in linkExistingWebResource command. 
Error code: undefined. 
Error message: Cannot set properties of undefined (setting '@_version'). 
Error stack: TypeError: Cannot set properties of undefined (setting '@_version')
	at t.xmlToJSON (c:\Users\msan\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.1\dist\extension.js:2:801897)
	at t.WebResourceHelper.<anonymous> (c:\Users\msan\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.1\dist\extension.js:2:762971)
	at Generator.next (<anonymous>)
	at o (c:\Users\msan\.vscode\extensions\danish-naglekar.dataverse-devtools-2.2.1\dist\extension.js:2:751513).

**Comment by Power-Maverick** [comment]
I'll look into this today. Thanks for raising this to my attention

**Comment by Power-Maverick** [comment]
I was not able to replicate the issue on my end based on what I understood the problem was. Can someone share the dvdt.linker.xml file so I can use that to replicate the issue?

**Comment by Power-Maverick** [comment]
The new version is released with the fix. Make sure to upgrade the version
