### ISSUE TITLE
[Bug]: doenst work after authentication

### ISSUE THREAD

**Issue by TiyaniMilton** [Power-Maverick/DataverseDevTools-VSCode#99]
### What happened?

After authentication it doesnt do anything, it keeps insisting that Im not signed-in 

### What version of the tool are you using?

v2.1.1

### Any relevant session id from VSCode?

3d291d92-bb60-4023-bac5-af615d3aaee81677832411103

### Relevant log output

```shell
Error occured in addConnection command. 
Error code: undefined. 
Error message: ChainedTokenCredential authentication failed.
CredentialUnavailableError: EnvironmentCredential is unavailable. No underlying credential could be used. To troubleshoot, visit https://aka.ms/azsdk/js/identity/environmentcredential/troubleshoot.
CredentialUnavailableError: ManagedIdentityCredential: Authentication failed. Message ManagedIdentityCredential - No MSI credential available
CredentialUnavailableError: Azure CLI could not be found. Please visit https://aka.ms/azure-cli for installation instructions and then, once installed, authenticate to your Azure account using 'az login'.
CredentialUnavailableError: The 'Az.Account' module >= 2.2.0 is not installed. Install the Azure Az PowerShell module with: "Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force".. 
Error stack: AggregateAuthenticationError: ChainedTokenCredential authentication failed.
CredentialUnavailableError: EnvironmentCredential is unavailable. No underlying credential could be used. To troubleshoot, visit https://aka.ms/azsdk/js/identity/environmentcredential/troubleshoot.
CredentialUnavailableError: ManagedIdentityCredential: Authentication failed. Message ManagedIdentityCredential - No MSI credential available
CredentialUnavailableError: Azure CLI could not be found. Please visit https://aka.ms/azure-cli for installation instructions and then, once installed, authenticate to your Azure account using 'az login'.
CredentialUnavailableError: The 'Az.Account' module >= 2.2.0 is not installed. Install the Azure Az PowerShell module with: "Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force".
    at \node_modules\@azure\identity\dist\index.js:2657:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.withSpan (\node_modules\@azure\core-tracing\dist\index.js:140:28).
```

**Comment by Power-Maverick** [comment]
What type of connection type you are using?
